#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o nounset -o pipefail
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
# (c) 2023 Farcloser <apostasie@farcloser.world>
# (c) 2019 Dubo Dubon Duponey <dubodubonduponey+github@pm.me>
# Distributed under the terms of the MIT license
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★

echo "★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★"
date
echo "Starting mumbrew..."

# Get to brew to get terminal-notifier
brew_exec="$(command -v brew || true)"
# This does not work as expected - instead, assume we are inside HOMEBREW_PREFIX (which the install formula does)
# brew_exec="${brew_exec:-$(dirname "$0")/../../../../bin/brew}"
brew_exec="${brew_exec:-$(pwd)/bin/brew}"

notifier="$($brew_exec --repository)/bin/terminal-notifier"

"$brew_exec" update >/dev/null 2>&1
outdated=$($brew_exec outdated --quiet | sed -e 's/.*\///')
pinned=$($brew_exec list --pinned)

# Remove pinned formulae from the list of outdated formulae
outdated=$(comm -1 -3 <(echo "$pinned") <(echo "$outdated"))

if [ -z "$outdated" ] ; then
  echo "Mumbrew: everything up to date"
  if [ -e "$notifier" ]; then
     $notifier \
        -title "Mumbrew" \
        -message "Everything up to date"
  fi
  exit
fi

if [ -e "$notifier" ]; then
  $notifier -title "Mumbrew: updating" -message "$outdated"
fi

$brew_exec upgrade
$brew_exec cleanup

if [ -e "$notifier" ]; then
  $notifier -title "Mumbrew" -message "Done updating!"
fi

echo "★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★"
