name: CI

on: [push, pull_request]

jobs:
  test:
    # https://github.com/actions/runner-images
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: true

      - name: test
        run: |
          brew install shellcheck
          ./test.sh
