name: CI

on: [push, pull_request]

jobs:
  test:
    # https://github.com/actions/runner-images
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checks-out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          submodules: true

      - name: test
        run: |
          brew install shellcheck
          ./test.sh
